name: Common Workflow

on: [workflow_call]

jobs:
  manageIssues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write

    steps:
      - name: Checkout book-reading-actions repository
        uses: actions/checkout@v2
        with:
          repository: hwahyeon/book-reading-actions
          path: book-reading-actions

      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          path: target-repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyyaml pygithub

      - name: Create Issues for Chapters
        run: |
          echo "Running create_issues.py"
          python ../book-reading-actions/scripts/create_issues.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        working-directory: target-repo

      - name: Close Issues for Completed Chapters
        run: |
          echo "Running close_issues.py"
          python ../book-reading-actions/scripts/close_issues.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        working-directory: target-repo

      - name: Commit and push changes
        run: |
          cd target-repo
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add issues.json
          if ! git diff --cached --quiet; then
            git commit -m "docs: Update issues data"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}